CREATE TABLE Activities (
  Id INTEGER NOT NULL AUTO_INCREMENT,
  Title VARCHAR(45) NOT NULL,
  DateUpdated TIMESTAMP NOT NULL,
  PRIMARY KEY (Id),
  UNIQUE KEY UNIQUE_Activities_Title (Title)
);

CREATE TABLE Roles (
  Id INTEGER NOT NULL AUTO_INCREMENT,
  Title VARCHAR(15) NOT NULL,
  DateUpdated TIMESTAMP NOT NULL,
  PRIMARY KEY (Id),
  UNIQUE KEY UNIQUE_Roles_Title (Title)
);

CREATE TABLE Users (
  Id INTEGER NOT NULL AUTO_INCREMENT,
  Username VARCHAR(45) NOT NULL,
  Password VARCHAR(60) DEFAULT NULL,
  Email VARCHAR(45) NOT NULL,
  Role INTEGER NOT NULL,
  Enabled TINYINT NOT NULL default '0',
  DateUpdated TIMESTAMP NOT NULL,
  PRIMARY KEY  (Id),
  UNIQUE KEY UNIQUE_Users_Username (Username),
  UNIQUE KEY UNIQUE_Users_Email (Email),
  FOREIGN KEY (Role) REFERENCES Roles (Id) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE Subtitles (
  Id INTEGER NOT NULL AUTO_INCREMENT,
  Title VARCHAR(45) NOT NULL,
  DateUpdated TIMESTAMP NOT NULL,
  PRIMARY KEY (Id),
  UNIQUE KEY UNIQUE_Subtitles_Title (Title)
);

CREATE TABLE Comments (
  Id INTEGER NOT NULL AUTO_INCREMENT,
  Title VARCHAR(45) NOT NULL,
  DateUpdated TIMESTAMP NOT NULL,
  PRIMARY KEY (Id),
  UNIQUE KEY UNIQUE_Comments_Title (Title)
);

CREATE TABLE Categories (
  Id INTEGER NOT NULL AUTO_INCREMENT,
  Title VARCHAR(45) NOT NULL,
  Parent INTEGER DEFAULT NULL,
  DateUpdated TIMESTAMP NOT NULL,
  PRIMARY KEY (Id),
  UNIQUE KEY UNIQUE_Categories_Title (Title),
  FOREIGN KEY (Parent) REFERENCES Categories (Id) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE Publishers (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Title VARCHAR(100) NOT NULL,
  DateUpdated TIMESTAMP NOT NULL,
  PRIMARY KEY (Id),
  UNIQUE KEY UNIQUE_Title (Title)
);

CREATE TABLE Artists (
  Id INTEGER NOT NULL AUTO_INCREMENT,
  Title VARCHAR(255) NOT NULL,
  Description TEXT,
  DateUpdated TIMESTAMP NOT NULL,
  PRIMARY KEY (Id),
  UNIQUE KEY UNIQUE_Artists_Title (Title)
);

CREATE TABLE Items (
  Id INTEGER NOT NULL AUTO_INCREMENT,
  TitleEng VARCHAR(255) NOT NULL,
  TitleEll VARCHAR(255) DEFAULT NULL,
  Category INTEGER NOT NULL,
  Publisher INTEGER DEFAULT NULL,
  PhotoPath VARCHAR(45) DEFAULT NULL,
  Description TEXT,
  Year INTEGER DEFAULT NULL,
  Rating INTEGER DEFAULT NULL,
  Subtitles INTEGER DEFAULT NULL,
  Discs INTEGER DEFAULT NULL,
  Place INTEGER DEFAULT NULL,
  Pages INTEGER DEFAULT NULL,
  DateUpdated TIMESTAMP NOT NULL,
  PRIMARY KEY (Id),
  FOREIGN KEY (Category) REFERENCES Categories (Id) ON DELETE NO ACTION ON UPDATE CASCADE,
  FOREIGN KEY (Publisher) REFERENCES Publishers (Id) ON DELETE NO ACTION ON UPDATE CASCADE,
  FOREIGN KEY (Subtitles) REFERENCES Subtitles (Id) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE CommentsItems (
  Id INTEGER NOT NULL AUTO_INCREMENT,
  IdItem INTEGER NOT NULL,
  IdComment INTEGER NOT NULL,
  DateUpdated TIMESTAMP NOT NULL,
  PRIMARY KEY (Id),
  UNIQUE KEY UNIQUE_CommentItems (IdItem, IdComment),
  FOREIGN KEY (IdComment) REFERENCES Comments (Id) ON DELETE NO ACTION ON UPDATE CASCADE,
  FOREIGN KEY (IdItem) REFERENCES Items (Id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ArtistsActivitiesItems (
  Id INTEGER NOT NULL AUTO_INCREMENT,
  IdArtist INTEGER NOT NULL,
  IdItem INTEGER NOT NULL,
  IdActivity INTEGER NOT NULL,
  DateUpdated TIMESTAMP NOT NULL,
  PRIMARY KEY (Id),
  UNIQUE KEY UNIQUE_ArtistsActivitiesItems (IdArtist, IdItem, IdActivity),
  FOREIGN KEY (IdActivity) REFERENCES Activities (Id) ON DELETE NO ACTION ON UPDATE CASCADE,
  FOREIGN KEY (IdArtist) REFERENCES Artists (Id) ON DELETE NO ACTION ON UPDATE CASCADE,
  FOREIGN KEY (IdItem) REFERENCES Items (Id) ON DELETE CASCADE ON UPDATE CASCADE
);